### ISSUE TITLE
Cannot read property 'Temp SC' of undefined

### ISSUE THREAD

**Issue by emailsbecker** [5k-mirrors/poe-what-to-flip#4]
Hi there.  I came across this tool after having built one that does some of what yours does.  It seems yours might do more, so I was thinking of abandoning mine and helping with yours.

I'm trying to check yours out in that sandbox, but it loads with an error: "Cannot read property 'Temp SC' of undefined" in /src/components/leagues.js:61:30 ... which is strange, because from what I see there selectedMetaLeague is defined on line 57.

Commenting out some of that and hardcoding that variable to "Standard" showed that the same error is thrown for 3 variables in that file, so I got the page to work by commenting out lines 57-62 and instead hard-coding those variables to = "Standard".

I'm not really a programmer by trade (long story) so my knowledge with js is limited.  Not sure why the problem exists, thought I would point it out to you and see what you think.

**Comment by emailsbecker** [comment]
Small correction: The page seems to be working but I see the links in the Incursion Uniques section all have Metamorph in them.  Not sure if the other results are valid either, I'm just saying I at least get the page to load.

**Comment by thisismydesign** [comment]
Hey, thanks for reporting the issue. Also, always happy for the support. :)

The issue was that there are no leagues currently.

http://api.pathofexile.com/leagues?type=main&compact=1
```
[{"id":"Standard","realm":"pc","url":"http:\/\/pathofexile.com\/forum\/view-thread\/71278","startAt":"2013-01-23T21:00:00Z","endAt":null,"delveEvent":true},{"id":"Hardcore","realm":"pc","url":"http:\/\/pathofexile.com\/forum\/view-thread\/71276","startAt":"2013-01-23T21:00:00Z","endAt":null,"delveEvent":true},{"id":"SSF Standard","realm":"pc","url":"http:\/\/pathofexile.com\/forum\/view-thread\/1841357","startAt":"2013-01-23T21:00:00Z","endAt":null,"delveEvent":true},{"id":"SSF Hardcore","realm":"pc","url":"http:\/\/pathofexile.com\/forum\/view-thread\/1841353","startAt":"2013-01-23T21:00:00Z","endAt":null,"delveEvent":true}]
```

Fixed in https://github.com/5k-mirrors/poe-what-to-flip/commit/607e7d9c0611abb75e2ff9d35f9e4c0691de975d
